Repository Team-studywithme/studyWithMe-BackEnd, pull requests merged in 2023-04, with the labels that each got.

#21 feature : "매칭 게시판을 구현한다"
  src/main/java/team/studywithme/api/controller/AccountApiController.java
  src/main/java/team/studywithme/api/controller/BoardApiController.java
  src/main/java/team/studywithme/api/controller/dto/response/BoardResponse.java
  src/main/java/team/studywithme/api/controller/dto/response/PostResponse.java
  src/main/java/team/studywithme/domain/entity/Post.java
  src/main/java/team/studywithme/repository/AvatarRepository.java
  src/main/java/team/studywithme/repository/BoardRepository.java
  src/main/java/team/studywithme/repository/PostRepository.java
  src/main/java/team/studywithme/service/AvatarService.java
  src/main/java/team/studywithme/service/BoardService.java
  src/main/java/team/studywithme/service/PostService.java
  src/main/java/team/studywithme/utils/kakao/KakaoAuthorizationInfo.java
  src/main/java/team/studywithme/utils/kakao/KakaoLoginUtils.java
  src/main/java/team/studywithme/utils/session/SessionUtils.java
  src/main/resources/application-local.yml
  src/main/resources/sql/data.sql
  src/test/java/resources/sql/data-test.sql
  src/test/resources/application.yml
  src/test/resources/sql/data-test.sql
Labels: backend, feature, setting

#24 feature : "게시물 API를 구현한다"
  src/main/java/team/studywithme/api/controller/PostApiController.java
  src/main/java/team/studywithme/api/controller/dto/response/CommentDetailResponse.java
  src/main/java/team/studywithme/api/controller/dto/response/PostDetailResponse.java
  src/main/java/team/studywithme/domain/entity/Board.java
  src/main/java/team/studywithme/repository/AvatarRepository.java
  src/main/java/team/studywithme/repository/CommentRepository.java
  src/main/java/team/studywithme/repository/PostRepository.java
  src/main/java/team/studywithme/service/AvatarService.java
  src/main/java/team/studywithme/service/CommentService.java
  src/main/java/team/studywithme/service/PostService.java
  src/main/resources/sql/data.sql
Labels: backend, feature

#31 refactor : "세션 로직을 리팩토링한다"
  build.gradle
  src/main/java/team/studywithme/api/controller/AccountApiController.java
  src/main/java/team/studywithme/api/controller/ApiController.java
  src/main/java/team/studywithme/api/controller/AvatarApiController.java
  src/main/java/team/studywithme/api/controller/BoardApiController.java
  src/main/java/team/studywithme/api/controller/PostApiController.java
  src/main/java/team/studywithme/api/controller/argumentresolver/SessionArgumentResolver.java
  src/main/java/team/studywithme/api/controller/dto/response/KakaoLoginResponse.java
  src/main/java/team/studywithme/api/controller/interceptor/LoginInterceptor.java
  src/main/java/team/studywithme/config/WebConfig.java
  src/main/java/team/studywithme/config/session/HttpSessionConfig.java
  src/main/java/team/studywithme/config/session/LoginAvatarId.java
  src/main/java/team/studywithme/domain/entity/Avatar.java
  src/main/java/team/studywithme/repository/AccountRepository.java
  src/main/java/team/studywithme/repository/AvatarRepository.java
  src/main/java/team/studywithme/repository/CommentRepository.java
  src/main/java/team/studywithme/repository/PostRepository.java
  src/main/java/team/studywithme/service/AccountService.java
  src/main/java/team/studywithme/service/AvatarService.java
  src/main/java/team/studywithme/service/BoardService.java
  src/main/java/team/studywithme/service/CommentService.java
  src/main/java/team/studywithme/service/PostService.java
  src/main/java/team/studywithme/utils/kakao/KakaoAuthorizationInfo.java
  src/main/java/team/studywithme/utils/kakao/KakaoLoginUtils.java
  src/main/java/team/studywithme/utils/session/AES.java
  src/main/java/team/studywithme/utils/session/SessionUtils.java
  src/main/resources/application-local.yml
  src/main/resources/sql/data.sql
  src/test/resources/sql/data-test.sql
Labels: backend, refactor

#35 위치 관련 기능 및 테스트 데이터 생성기능
  src/main/java/team/studywithme/api/controller/LocationApiController.java
  src/main/java/team/studywithme/api/controller/dto/request/MyLocationRequest.java
  src/main/java/team/studywithme/api/controller/dto/response/LocationListResponse.java
  src/main/java/team/studywithme/api/controller/dto/response/LocationResponse.java
  src/main/java/team/studywithme/api/controller/dto/response/MyLocationResponse.java
  src/main/java/team/studywithme/config/WebConfig.java
  src/main/java/team/studywithme/domain/entity/Location.java
  src/main/java/team/studywithme/repository/LocationRepository.java
  src/main/java/team/studywithme/service/LocationService.java
  src/main/resources/application-local.yml
Labels: backend, feature
